const STYLISH_WHITE = '#fff';
const STYLISH_BLACK = '#000';

// bg
const STYLISH_BG_LIGHT = '#EDF0F8';
const STYLISH_BG_DARK = '#1a1b24';

// text
const STYLISH_TEXT_LIGHT = '#11181C';
const STYLISH_TEXT_DARK = '#ECEDEE';

// primary
const STYLISH_PRIMARY_LIGHT = '#1B84FF';
const STYLISH_PRIMARY_DARK = '#006AE6';

const STYLISH_LIGHT_PRIMARY_LIGHT = '#E9F3FF';
const STYLISH_LIGHT_PRIMARY_DARK = '#172331';

// danger
const STYLISH_DANGER_LIGHT = '#F8285A';
const STYLISH_DANGER_DARK = '#E42855';

const STYLISH_LIGHT_DANGER_LIGHT = '#FFEEF3';
const STYLISH_LIGHT_DANGER_DARK = '#302024';

// success
const STYLISH_SUCCESS_LIGHT = '#17C653';
const STYLISH_SUCCESS_DARK = '#00A261';

const STYLISH_LIGHT_SUCCESS_LIGHT = '#EAFFF1';
const STYLISH_LIGHT_SUCCESS_DARK = '#1F2623';

// secondary
const STYLISH_SECONDARY_LIGHT = '#F1F1F4';
const STYLISH_SECONDARY_DARK = '#363843';

const STYLISH_LIGHT_SECONDARY_LIGHT = '#F9F9F9';
const STYLISH_LIGHT_SECONDARY_DARK = '#363843';

// info
const STYLISH_INFO_LIGHT = '#7239EA';
const STYLISH_INFO_DARK = '#883FFF';

const STYLISH_LIGHT_INFO_LIGHT = '#F8F5FF';
const STYLISH_LIGHT_INFO_DARK = '#272134';

// warning
const STYLISH_WARNING_LIGHT = '#F6C000';
const STYLISH_WARNING_DARK = '#C59A00';

const STYLISH_LIGHT_WARNING_LIGHT = '#FFF8DD';
const STYLISH_LIGHT_WARNING_DARK = '#242320';

// brand
const STYLISH_BRAND_LIGHT = '#FF6F1E';
const STYLISH_BRAND_DARK = '#D74E00';

const STYLISH_LIGHT_BRAND_LIGHT = '#FFF5EF';
const STYLISH_LIGHT_BRAND_DARK = '#272320';

// gray
const STYLISH_GRAY_100_LIGHT = '#F9F9F9';
const STYLISH_GRAY_200_LIGHT = '#F1F1F4';
const STYLISH_GRAY_300_LIGHT = '#DBDFE9';
const STYLISH_GRAY_400_LIGHT = '#C4CADA';
const STYLISH_GRAY_500_LIGHT = '#99A1B7';
const STYLISH_GRAY_600_LIGHT = '#78829D';
const STYLISH_GRAY_700_LIGHT = '#4B5675';
const STYLISH_GRAY_800_LIGHT = '#252F4A';
const STYLISH_GRAY_900_LIGHT = '#071437';

const STYLISH_GRAY_100_DARK = '#1B1C22';
const STYLISH_GRAY_200_DARK = '#26272F';
const STYLISH_GRAY_300_DARK = '#363843';
const STYLISH_GRAY_400_DARK = '#464852';
const STYLISH_GRAY_500_DARK = '#636674';
const STYLISH_GRAY_600_DARK = '#808290';
const STYLISH_GRAY_700_DARK = '#9A9CAE';
const STYLISH_GRAY_800_DARK = '#B5B7C8';
const STYLISH_GRAY_900_DARK = '#F5F5F5';

export const Colors = {
  light: {
    light: STYLISH_WHITE,
    dark: STYLISH_BLACK,
    screenBackground: STYLISH_BG_LIGHT,
    text: STYLISH_TEXT_LIGHT,
    primary: STYLISH_PRIMARY_LIGHT,
    lightPrimary: STYLISH_LIGHT_PRIMARY_LIGHT,
    danger: STYLISH_DANGER_LIGHT,
    lightDanger: STYLISH_LIGHT_DANGER_LIGHT,
    success: STYLISH_SUCCESS_LIGHT,
    lightSuccess: STYLISH_LIGHT_SUCCESS_LIGHT,
    secondary: STYLISH_SECONDARY_LIGHT,
    lightSecondary: STYLISH_LIGHT_SECONDARY_LIGHT,
    info: STYLISH_INFO_LIGHT,
    lightInfo: STYLISH_LIGHT_INFO_LIGHT,
    warning: STYLISH_WARNING_LIGHT,
    lightWarning: STYLISH_LIGHT_WARNING_LIGHT,
    brand: STYLISH_BRAND_LIGHT,
    lightBrand: STYLISH_LIGHT_BRAND_LIGHT,
    gray100: STYLISH_GRAY_100_LIGHT,
    gray200: STYLISH_GRAY_200_LIGHT,
    gray300: STYLISH_GRAY_300_LIGHT,
    gray400: STYLISH_GRAY_400_LIGHT,
    gray500: STYLISH_GRAY_500_LIGHT,
    gray600: STYLISH_GRAY_600_LIGHT,
    gray700: STYLISH_GRAY_700_LIGHT,
    gray800: STYLISH_GRAY_800_LIGHT,
    gray900: STYLISH_GRAY_900_LIGHT,
  },
  dark: {
    light: STYLISH_BG_DARK,
    dark: STYLISH_WHITE,
    screenBackground: STYLISH_BG_DARK,
    text: STYLISH_TEXT_DARK,
    primary: STYLISH_PRIMARY_DARK,
    lightPrimary: STYLISH_LIGHT_PRIMARY_DARK,
    danger: STYLISH_DANGER_DARK,
    lightDanger: STYLISH_LIGHT_DANGER_DARK,
    success: STYLISH_SUCCESS_DARK,
    lightSuccess: STYLISH_LIGHT_SUCCESS_DARK,
    secondary: STYLISH_SECONDARY_DARK,
    lightSecondary: STYLISH_LIGHT_SECONDARY_DARK,
    info: STYLISH_INFO_DARK,
    lightInfo: STYLISH_LIGHT_INFO_DARK,
    warning: STYLISH_WARNING_DARK,
    lightWarning: STYLISH_LIGHT_WARNING_DARK,
    brand: STYLISH_BRAND_DARK,
    lightBrand: STYLISH_LIGHT_BRAND_DARK,
    gray100: STYLISH_GRAY_100_DARK,
    gray200: STYLISH_GRAY_200_DARK,
    gray300: STYLISH_GRAY_300_DARK,
    gray400: STYLISH_GRAY_400_DARK,
    gray500: STYLISH_GRAY_500_DARK,
    gray600: STYLISH_GRAY_600_DARK,
    gray700: STYLISH_GRAY_700_DARK,
    gray800: STYLISH_GRAY_800_DARK,
    gray900: STYLISH_GRAY_900_DARK,
  },
};
