const TRENDY_WHITE = '#fff';
const TRENDY_BLACK = '#000';

// bg
const TRENDY_BG_LIGHT = '#EDF0F8';
const TRENDY_BG_DARK = '#1a1b24';

// text
const TRENDY_TEXT_LIGHT = '#11181C';
const TRENDY_TEXT_DARK = '#ECEDEE';

// primary
const TRENDY_PRIMARY_LIGHT = '#1B84FF';
const TRENDY_PRIMARY_DARK = '#006AE6';

const TRENDY_LIGHT_PRIMARY_LIGHT = '#E9F3FF';
const TRENDY_LIGHT_PRIMARY_DARK = '#172331';

// danger
const TRENDY_DANGER_LIGHT = '#F8285A';
const TRENDY_DANGER_DARK = '#E42855';

const TRENDY_LIGHT_DANGER_LIGHT = '#FFEEF3';
const TRENDY_LIGHT_DANGER_DARK = '#302024';

// success
const TRENDY_SUCCESS_LIGHT = '#17C653';
const TRENDY_SUCCESS_DARK = '#00A261';

const TRENDY_LIGHT_SUCCESS_LIGHT = '#EAFFF1';
const TRENDY_LIGHT_SUCCESS_DARK = '#1F2623';

// secondary
const TRENDY_SECONDARY_LIGHT = '#F1F1F4';
const TRENDY_SECONDARY_DARK = '#363843';

const TRENDY_LIGHT_SECONDARY_LIGHT = '#F9F9F9';
const TRENDY_LIGHT_SECONDARY_DARK = '#363843';

// info
const TRENDY_INFO_LIGHT = '#7239EA';
const TRENDY_INFO_DARK = '#883FFF';

const TRENDY_LIGHT_INFO_LIGHT = '#F8F5FF';
const TRENDY_LIGHT_INFO_DARK = '#272134';

// warning
const TRENDY_WARNING_LIGHT = '#F6C000';
const TRENDY_WARNING_DARK = '#C59A00';

const TRENDY_LIGHT_WARNING_LIGHT = '#FFF8DD';
const TRENDY_LIGHT_WARNING_DARK = '#242320';

// brand
const TRENDY_BRAND_LIGHT = '#FF6F1E';
const TRENDY_BRAND_DARK = '#D74E00';

const TRENDY_LIGHT_BRAND_LIGHT = '#FFF5EF';
const TRENDY_LIGHT_BRAND_DARK = '#272320';

// gray
const TRENDY_GRAY_100_LIGHT = '#F9F9F9';
const TRENDY_GRAY_200_LIGHT = '#F1F1F4';
const TRENDY_GRAY_300_LIGHT = '#DBDFE9';
const TRENDY_GRAY_400_LIGHT = '#C4CADA';
const TRENDY_GRAY_500_LIGHT = '#99A1B7';
const TRENDY_GRAY_600_LIGHT = '#78829D';
const TRENDY_GRAY_700_LIGHT = '#4B5675';
const TRENDY_GRAY_800_LIGHT = '#252F4A';
const TRENDY_GRAY_900_LIGHT = '#071437';

const TRENDY_GRAY_100_DARK = '#1B1C22';
const TRENDY_GRAY_200_DARK = '#26272F';
const TRENDY_GRAY_300_DARK = '#363843';
const TRENDY_GRAY_400_DARK = '#464852';
const TRENDY_GRAY_500_DARK = '#636674';
const TRENDY_GRAY_600_DARK = '#808290';
const TRENDY_GRAY_700_DARK = '#9A9CAE';
const TRENDY_GRAY_800_DARK = '#B5B7C8';
const TRENDY_GRAY_900_DARK = '#F5F5F5';

export const Colors = {
  light: {
    light: TRENDY_WHITE,
    dark: TRENDY_BLACK,
    screenBackground: TRENDY_BG_LIGHT,
    text: TRENDY_TEXT_LIGHT,
    primary: TRENDY_PRIMARY_LIGHT,
    lightPrimary: TRENDY_LIGHT_PRIMARY_LIGHT,
    danger: TRENDY_DANGER_LIGHT,
    lightDanger: TRENDY_LIGHT_DANGER_LIGHT,
    success: TRENDY_SUCCESS_LIGHT,
    lightSuccess: TRENDY_LIGHT_SUCCESS_LIGHT,
    secondary: TRENDY_SECONDARY_LIGHT,
    lightSecondary: TRENDY_LIGHT_SECONDARY_LIGHT,
    info: TRENDY_INFO_LIGHT,
    lightInfo: TRENDY_LIGHT_INFO_LIGHT,
    warning: TRENDY_WARNING_LIGHT,
    lightWarning: TRENDY_LIGHT_WARNING_LIGHT,
    brand: TRENDY_BRAND_LIGHT,
    lightBrand: TRENDY_LIGHT_BRAND_LIGHT,
    gray100: TRENDY_GRAY_100_LIGHT,
    gray200: TRENDY_GRAY_200_LIGHT,
    gray300: TRENDY_GRAY_300_LIGHT,
    gray400: TRENDY_GRAY_400_LIGHT,
    gray500: TRENDY_GRAY_500_LIGHT,
    gray600: TRENDY_GRAY_600_LIGHT,
    gray700: TRENDY_GRAY_700_LIGHT,
    gray800: TRENDY_GRAY_800_LIGHT,
    gray900: TRENDY_GRAY_900_LIGHT,
  },
  dark: {
    light: TRENDY_BLACK,
    dark: TRENDY_WHITE,
    screenBackground: TRENDY_BG_DARK,
    text: TRENDY_TEXT_DARK,
    primary: TRENDY_PRIMARY_DARK,
    lightPrimary: TRENDY_LIGHT_PRIMARY_DARK,
    danger: TRENDY_DANGER_DARK,
    lightDanger: TRENDY_LIGHT_DANGER_DARK,
    success: TRENDY_SUCCESS_DARK,
    lightSuccess: TRENDY_LIGHT_SUCCESS_DARK,
    secondary: TRENDY_SECONDARY_DARK,
    lightSecondary: TRENDY_LIGHT_SECONDARY_DARK,
    info: TRENDY_INFO_DARK,
    lightInfo: TRENDY_LIGHT_INFO_DARK,
    warning: TRENDY_WARNING_DARK,
    lightWarning: TRENDY_LIGHT_WARNING_DARK,
    brand: TRENDY_BRAND_DARK,
    lightBrand: TRENDY_LIGHT_BRAND_DARK,
    gray100: TRENDY_GRAY_100_DARK,
    gray200: TRENDY_GRAY_200_DARK,
    gray300: TRENDY_GRAY_300_DARK,
    gray400: TRENDY_GRAY_400_DARK,
    gray500: TRENDY_GRAY_500_DARK,
    gray600: TRENDY_GRAY_600_DARK,
    gray700: TRENDY_GRAY_700_DARK,
    gray800: TRENDY_GRAY_800_DARK,
    gray900: TRENDY_GRAY_900_DARK,
  },
};
